# Generated by Django 4.0.1 on 2022-01-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
